name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  actions: write

jobs:
  # Cleanup old workflow runs (keep only last 3)
  cleanup:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 3

  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Configure npm (Windows optimization)
        if: runner.os == 'Windows'
        run: |
          npm config set fund false
          npm config set audit false
          npm config set progress false

      - name: Install dependencies
        run: npm ci

      - name: Download and prepare Apple2TS (macOS/Linux)
        if: runner.os != 'Windows'
        run: npx tsx scripts/download-apple2ts.ts

      - name: Download and prepare Apple2TS (Windows)
        if: runner.os == 'Windows'
        run: npx tsx scripts/download-apple2ts.ts
        shell: pwsh

      # macOS Code Signing Setup
      - name: Setup macOS signing
        if: runner.os == 'macOS'
        env:
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
        run: |
          # Create certificate from base64 string and install it
          if [ -n "$APPLE_CERTIFICATE" ]; then
            echo $APPLE_CERTIFICATE | base64 --decode > certificate.p12
            security create-keychain -p actions build.keychain
            security default-keychain -s build.keychain
            security unlock-keychain -p actions build.keychain
            
            # Import certificate with empty password (trim any whitespace from secret)
            CERT_PASSWORD=$(echo "$APPLE_CERTIFICATE_PASSWORD" | xargs)
            if [ -z "$CERT_PASSWORD" ] || [ "$CERT_PASSWORD" = " " ]; then
              security import certificate.p12 -k build.keychain -P "" -T /usr/bin/codesign
            else
              security import certificate.p12 -k build.keychain -P "$CERT_PASSWORD" -T /usr/bin/codesign
            fi
            
            security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k actions build.keychain
            
            # Set up signing identity
            IDENTITY=$(security find-identity -v -p codesigning build.keychain | head -1 | grep '"' | sed -e 's/[^"]*"//' -e 's/".*//')
            echo "APPLE_IDENTITY=$IDENTITY" >> $GITHUB_ENV
          else
            echo "No Apple certificate found, building unsigned"
            echo "SKIP_CODE_SIGNING=true" >> $GITHUB_ENV
          fi

      - name: Build application
        run: npm run make
        env:
          # Optimize Windows builds
          NODE_OPTIONS: "--max-old-space-size=4096"

      - name: Upload build artifacts (macOS)
        if: runner.os == 'macOS'
        uses: eXhumer/upload-artifact@0b7d5f5684d3f642f978d2faad9ade64f5b4dd57
        with:
          name: build-artifacts-${{ matrix.os }}
          path: out/
          follow-symlinks: false
          if-no-files-found: error
          compression-level: 9

      - name: Upload build artifacts (Linux/Windows)
        if: runner.os != 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ matrix.os }}
          path: out/
          retention-days: 3