name: Build and Release

on:
  push:
    tags:
      - 'v*' # Triggers on version tags like v1.0.0, v1.0.1, etc.
  workflow_dispatch: # Allows manual triggering from GitHub UI

# Grant necessary permissions for release publishing
permissions:
  contents: write
  actions: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  # Cleanup old workflow runs (keep only last 3)
  cleanup:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 3

  release:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Configure npm (Windows optimization)
        if: runner.os == 'Windows'
        run: |
          npm config set fund false
          npm config set audit false
          npm config set progress false

      - name: Install dependencies
        run: npm ci

      - name: Download and prepare Apple2TS (macOS/Linux)
        if: runner.os != 'Windows'
        run: npx tsx scripts/download-apple2ts.ts

      - name: Download and prepare Apple2TS (Windows)
        if: runner.os == 'Windows'
        run: npx tsx scripts/download-apple2ts.ts
        shell: pwsh

      # macOS Code Signing Setup
      - name: Setup macOS signing
        if: runner.os == 'macOS'
        env:
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: |
          # Create certificate from base64 string and install it
          if [ -n "$APPLE_CERTIFICATE" ]; then
            echo $APPLE_CERTIFICATE | base64 --decode > certificate.p12
            security create-keychain -p actions build.keychain
            security default-keychain -s build.keychain
            security unlock-keychain -p actions build.keychain
            
            # Import certificate with empty password (trim any whitespace from secret)
            CERT_PASSWORD=$(echo "$APPLE_CERTIFICATE_PASSWORD" | xargs)
            if [ -z "$CERT_PASSWORD" ] || [ "$CERT_PASSWORD" = " " ]; then
              security import certificate.p12 -k build.keychain -P "" -T /usr/bin/codesign
            else
              security import certificate.p12 -k build.keychain -P "$CERT_PASSWORD" -T /usr/bin/codesign
            fi
            
            security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k actions build.keychain
            
            # Set up signing identity
            IDENTITY=$(security find-identity -v -p codesigning build.keychain | head -1 | grep '"' | sed -e 's/[^"]*"//' -e 's/".*//')
            echo "APPLE_IDENTITY=$IDENTITY" >> $GITHUB_ENV
            
            # Set up app-specific password in keychain for notarization
            if [ -n "$APPLE_ID_PASSWORD" ]; then
              xcrun notarytool store-credentials "notarytool-profile" \
                --apple-id "$APPLE_ID" \
                --team-id "$APPLE_TEAM_ID" \
                --password "$APPLE_ID_PASSWORD"
              echo "APPLE_ID_PASSWORD=@keychain:notarytool-profile" >> $GITHUB_ENV
            fi
          else
            echo "No Apple certificate found, building unsigned"
            echo "SKIP_CODE_SIGNING=true" >> $GITHUB_ENV
          fi

      # Windows Code Signing Setup  
      - name: Setup Windows signing
        if: runner.os == 'Windows'
        env:
          WINDOWS_CERTIFICATE: ${{ secrets.WINDOWS_CERTIFICATE }}
          WINDOWS_CERTIFICATE_PASSWORD: ${{ secrets.WINDOWS_CERTIFICATE_PASSWORD }}
        run: |
          if ($env:WINDOWS_CERTIFICATE) {
            [System.Convert]::FromBase64String($env:WINDOWS_CERTIFICATE) | Set-Content -Path certificate.p12 -Encoding Byte
            $env:CSC_LINK = "certificate.p12"
            $env:CSC_KEY_PASSWORD = $env:WINDOWS_CERTIFICATE_PASSWORD
            echo "CSC_LINK=certificate.p12" >> $env:GITHUB_ENV
            echo "CSC_KEY_PASSWORD=$env:WINDOWS_CERTIFICATE_PASSWORD" >> $env:GITHUB_ENV
          } else {
            echo "No Windows certificate found, building unsigned"
            echo "SKIP_CODE_SIGNING=true" >> $env:GITHUB_ENV
          }
        shell: pwsh

      - name: Build and publish (with signing)
        if: env.SKIP_CODE_SIGNING != 'true' || runner.os == 'Windows'
        run: npm run publish
        env:
          # Optimize Windows builds
          NODE_OPTIONS: "--max-old-space-size=4096"

      - name: Build and publish (unsigned)
        if: env.SKIP_CODE_SIGNING == 'true' && runner.os != 'Windows'
        run: npm run publish:unsigned
        env:
          # Optimize Windows builds
          NODE_OPTIONS: "--max-old-space-size=4096"
